### PR TITLE
Live Activity support update

### PR DESCRIPTION
**Pull request by fhboswell**
# Description
## Summary
Live Activity support version bumped from `3.12.2` to `3.12.3`
Updates to the react native bridge to properly handle success closure.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/onesignal/react-native-onesignal/1456)

### CODE REVIEW

**Review by emawby — APPROVED** [review]

**Review by jkasten2 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/react-native-onesignal/1456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nan-li)

**Comment by nan-li** [comment]
Does changing the `dist` dir structure cause any side effects for end users, if the file path is now different?

**Review by nan-li — CHANGES_REQUESTED** [review]
Do these need to change with `dist` restructure?
https://github.com/OneSignal/react-native-onesignal/blob/7e6e148daf9f84ed2887f66067a1ae1ce97d0418/package.json#L5-L6

https://github.com/OneSignal/react-native-onesignal/blob/7e6e148daf9f84ed2887f66067a1ae1ce97d0418/package.json#L10

**Comment by nan-li** [comment]
Unrelated to this particular PR but for releasing the SDK.
I realized we have not released this SDK since before qualitython so we need to test or check everything is in order before releasing. For example the `index.test.ts` added during qualitython is giving `tsc` errors for me.

**Comment by fhboswell** [comment]
> Does changing the dist dir structure cause any side effects for end users, if the file path is now different?

I would like to keep the `dist` structure the same, this is why I am moving __tests__

**Comment by fhboswell** [comment]
Removed tests until user model. Tested enter and exit live activity, both work as expected (the server returns an error).

**Review by nan-li — APPROVED** [review]

**Pull request merged**
