### PR TITLE
Remove deprecated method for RN 0.47 compat

### PR DESCRIPTION
**Pull request by forki**
The component doesn't compile in RN 0.47-rc5 - discussion at https://github.com/facebook/react-native/issues/15232

### CODE REVIEW

**Comment by lukewlms** [comment]
Recommend checking out #294, just removing the @Override marker - that should be compatible with 0.46.x and 0.47.x.

This change as-is, I believe, will break 0.46.x.

**Comment by forki** [comment]
Yes. Seems my crying has been heard finally

**Comment by forki** [comment]
I think I let this open until you decide which way to go.

**Comment by tapz** [comment]
As #294 has been merged it would nice to release a new npm version.

**Comment by lukewlms** [comment]
#294 already merged - this can indeed be closed and we need an npm version!  Thanks a lot.

**Pull request closed without merging**
