### PR TITLE
Listen NetInfo connectionChange event (change deprecated)

### LINKED ISSUE #313: NetInfo's "change" event is deprecated
After upgrading to latest React Native (0.48.0) I keep getting this warning:

`NetInfo's "change" event is deprecated. Listen to the "connectionChange" event instead.`

I guess this is due to: https://github.com/geektimecoil/react-native-onesignal/blob/88f00a6f30bbf2986a570f908cff877b8ef71883/index.js#L20

### PR DESCRIPTION
**Pull request by ghost**
Fixes #313

### CODE REVIEW

**Comment by EricPKerr** [comment]
@geektimecoil bump. Should be a quick fix/release.  Thanks!

**Comment by ujwal-setlur** [comment]
Any ETA on merging this?

**Comment by almostintuitive** [comment]
It'd be great to merge this in and release a new version, the yellow box is quite annoying!:)

**Comment by ghost** [comment]
Still needs to get published on npm.

**Comment by jkasten2** [comment]
@avishayil Can you publish this update to npm? I don't have access on my account to do so.

**Comment by richeterre** [comment]
Hi @avishayil and @jkasten2, any update on getting this released now that the fix was merged? ☺️

**Comment by alimek** [comment]
+1 we need npm release with this

**Comment by Under-Warz** [comment]
+1 for npm update

**Comment by adriantombu** [comment]
Just got into the same problem after upgrading my app, hope it will be merged someday in the future  🙇

**Comment by ujwal-setlur** [comment]
@adriantombu, it's already merged.

**Comment by alimek** [comment]
@ujwal-setlur but after the merge it was not published to NPM as new version.

**Comment by ujwal-setlur** [comment]
I thought I just checked last night, and it was there. Will check again

**Comment by wysiecki** [comment]
hi, any news on this ? still getting this message

thx

**Pull request merged**
