### PR TITLE
fix for breaking iOS header change in RN 0.40.0

### LINKED ISSUE #130: Support for RN 0.40
As expressed [here](https://github.com/facebook/react-native/releases/tag/v0.40.0) all packages are now incompatible with 0.40. Any chance for an update?

### PR DESCRIPTION
**Pull request by danieldkim**
For the breaking "iOS native headers moved" [change in RN  0.40.0](https://github.com/facebook/react-native/releases/tag/v0.40.0).  Fixes #130.  Addresses facebook/react-native#11725.

### CODE REVIEW

**Comment by noris666** [comment]
Good fix. Thx. Contributors please merge this PR 👍

**Comment by hellogerard** [comment]
Consider making a major version bump, since this is a breaking change (after these changes, it will no longer work with React Native <= 0.39).

**Comment by avishayil** [comment]
Version 2 would support RN <= 0.39,
This PR will be merged to Version 3 that would be updated in parallel to Version 2.

**Comment by danieldkim** [comment]
@avishayil OK will Version 3 be on master or another branch?

**Pull request merged**
