### PR TITLE
Allowed to send extra parameters and added ability to send hidden messages.

### LINKED ISSUE #115: How do I send silent notifications on Android?
Do you plan to add support for silent notifications?

I would love to send notifications to the App to tell it to reload the data like it works on iOS with empty data and content_available=true

I asked about it from OneSignal and I got a reply from them:
"You can follow our Background Data and Notification Overriding guide for Android silent notifications but this can only be used with Native Java code." https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding

### PR DESCRIPTION
**Pull request by bitsal**
Hidden messages were verified on Android. On iOS it should work out-of-the-box using empty `contents` and `content_available=1`.

It should fix https://github.com/geektimecoil/react-native-onesignal/issues/115

### CODE REVIEW

**Comment by controversialUser** [comment]
can you show us an example how to use it for android please ?

**Comment by bitsal** [comment]
The same like for iOS
e.g.
```
OneSignal.postNotification({ en: 'Message' }, { prop1: '1', prop2: 5 }, playerId, { priority: 10 });
```

**Comment by controversialUser** [comment]
well i made all the changes you made in 4 files , and than executed the code you gave me: 

OneSignal.postNotification({ en: 'Message' }, { prop1: '1', prop2: 5 }, playerId, { priority: 10 });

but still not working for android ... have you tested this ?

**Comment by bitsal** [comment]
@controversialUser of course, it was required for our project app. Our team tested it a lot during the last week.

What exactly doesn't work for you? If you mean new `hidden` parameter. It will work only after you add it to your `AndroidManifest.xml` how it is described [here](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding). 
E.g. our version
```
<application
      android:name=".MainApplication"
      android:theme="@style/AppTheme"
...>

      <activity ...>
          ...
      </activity>

      <service
        android:name="com.geektime.rnonesignalandroid.NotificationNotDisplayingExtender"
        android:exported="false">
        <intent-filter>
          <action android:name="com.onesignal.NotificationExtender" />
        </intent-filter>
      </service>
    </application>
```

**Comment by controversialUser** [comment]
well when my app is open in android and i get a notification , an alert comes to the screen ... i dont want that alert , in ios is ok , but what can i do in android to prevent that alert ... have your team found a solution ?

**Comment by bitsal** [comment]
@controversialUser I guess you mean `OneSignal.inFocusDisplaying(2);` - it works only for Android.
All options: 0 -> None, 1 -> InAppAlert, 2 -> Notification.

It is not related to new changes.

**Comment by jamieparkinson** [comment]
@controversialUser to be clear; are you adding `hidden: true` to the final argument of `OneSignal.postNotification`? To be explicit:
```
OneSignal.postNotification(
    { }, // No content
    { foo: 'bar' }, // data
    playerId, // recipient
    // other params, as introduced in this PR
    {
        priority: 10,
        android_visibility: -1,
        hidden: true
    }
)
```
@avishayil looking forward to this getting merged! :slightly_smiling_face:

**Comment by controversialUser** [comment]
@jamieparkinson "hidden: true" helped me , thanks a lot ... @bitsal you are a hero bro , thanks for all :)

**Comment by Ouadie** [comment]
This PR do the job, could you please merge it!

**Comment by bitsal** [comment]
Is anybody going to review it? I wonder why it is in review status so long. 9 days from the last comment

**Comment by loiclouvet** [comment]
Good job, waiting for it to be merged ! :+1:

**Comment by jkasten2** [comment]
@avishayil This looks good to me. Could you merge this?

**Comment by maxs15** [comment]
Tested on my side as well, working well good job 👍 
Android is now working like IOS, my push with ``content_available=1``is silent without specifying the hidden parameter.

**Comment by floydus** [comment]
Would be nice to have a complete example including path of any Java classes and AndroidManifest.
I'm having the same issue, works perfectly after editing AppDelegate in iOS, but for Android, no f... luck.

**Comment by bitsal** [comment]
@floydus could you describe your issue in detail (I will try to help)? I've described all changes above what we did to make it work (`AndroidManifest` is also there). 
BTW, I didn't mention any changes that are in origin react-native-onesignal documentation. Everybody can read them there. No extra changes are required for `AppDelegate`.

**Comment by illright** [comment]
Does this pull request affect only P2P notifications? I'm looking for a way to silently process notifications that are sent programmatically through an API. Is this what I'm looking for?

**Comment by bitsal** [comment]
From the server, you could send all parameters before my changes I guess.

**Comment by isaaclem** [comment]
@bitsal: Thank you very much on your helps. However I'm wondering if it's gonna support if the app has been killed? I'm testing on Android Emulator with below curl
```
curl --include \
     --request POST \
     --header "Content-Type: application/json; charset=utf-8" \
     --data-binary "{\"app_id\": \"xxx\",
\"contents\": {},
\"content_available\": 1,
\"include_player_ids\": [\"xxxx\"]}" \
https://onesignal.com/api/v1\/notifications
```

When the app is in background or foreground, it's working fine, however if the app has been killed, event doesn't seems to be triggered. Is this a known issue?

**Comment by bitsal** [comment]
@isaaclem It didn't work for me either with that version of this library for a case when app is closed. Please check official documentation about whether it is possible just to be sure it is possible or an issue on SDK/library side.

**Pull request merged**
