### PR TITLE
Add some methods

### PR DESCRIPTION
**Pull request by haikov**
Hey!

I added implementation of some methods

### CODE REVIEW

**Comment by avishayil** [comment]
Thanks @gaykov , i'll take a look on this.
You're more than welcome to submit more PR's if you see any mistakes, feature request or whatever!

**Comment by haikov** [comment]
Hi @avishayil, any news? I need this functionality in production:)

**Comment by avishayil** [comment]
Hi @gaykov, I can't find the time to add the JS implementation myself. Can you pull the trigger?

**Comment by haikov** [comment]
sorry, I failed the rebase. I'll open a new PR

**Comment by haikov** [comment]
@avishayil finally: #7

**Pull request closed without merging**
