### PR TITLE
Add some android methods

### PR DESCRIPTION
**Pull request by haikov**

### CODE REVIEW

**Comment by avishayil** [comment]
Hi, thanks for the PR.
I've been arguing with myself what should be the default values for:

enableVibrate - battery drain when true?
enableInAppAlertNotification - UX wise annoying, default to false according to OneSignal.

Can you change those to false?

**Comment by haikov** [comment]
Do you think that we need to override default OneSignal settings? enableVibrate is true by default and it's OK, I think. It will be confusing for the users if the behaviour of the lib will not be as same as described in OneSignal documentation.

**Comment by avishayil** [comment]
OK, agreed with enableVibrate, but enableInAppNotification should set to false.

**Comment by haikov** [comment]
It's false by default. As describer in documentation here: https://documentation.onesignal.com/docs/android-sdk-api#section-enableinappalertnotification "By default this is false and notifications will not be shown when the user is in your app, instead the NotificationOpenedHandler is fired."

**Comment by avishayil** [comment]
My bad, just now noticed that you haven't override anything...
Testing and merging.

**Comment by haikov** [comment]
@avishayil thanks! can you please also update the npm version?

**Comment by avishayil** [comment]
Done

**Pull request merged**
