### PR TITLE
Fix opened event does not work when program is closed in Android

### PR DESCRIPTION
**Pull request by invisal**
Sometimes Android broadcast the opened event before Javascript could even add the event listener. Therefore, sometimes the opened event will never be triggered. To solve this problem, 

- First we start to listen to the event as soon as possible. We will cache the data if we receive
- When we add the event, it will use cached data if we have.

This problem is related to these issues #332 #339 #293 #279 #237 

I have used this code in production for 3 weeks so far without any problem so far.

### CODE REVIEW

**Comment by filbertteo** [comment]
tried it out and can confirm that it works, at least for the opened event (which is the primary use case anyway). hope it gets merged into master soon! good job @invisal !

**Comment by rayashi** [comment]
Please merge it!

**Comment by hcyildirim** [comment]
Im really happy about this pr, please merge it as soon as possible. Thank you @invisal

**Comment by pacozaa** [comment]
+1

**Review by arindam89 — APPROVED** [review]
I have tested this change. It works wonderfully.

**Comment by arindam89** [comment]
Thanks a lot @invisal

**Comment by ghost** [comment]
Thanks so much, this is brilliant!

**Comment by kashsbd** [comment]
Still not working guys.Do you  know how to resolve this ?

**Pull request merged**
