### PR TITLE
Upgrade to the latest OneSignal iOS SDK v2.5.4

### LINKED ISSUE #275: sendTags not saving
I am calling `OneSignal.sendTags({...})` on the callback for `ids` when there is a value for pushToken.  This happens during the signup process when the user initially accepts the push notification prompt which gets triggered by `OneSignal.registerForPushNotifications()`.  Yet, when I check the dashboard, I do not see the tags being saved.  I've noticed that sometimes if I restart the app, the tags would show up on the dashboard due to the same callbacks.  Not sure if there is a race condition or if I'm calling sendTags incorrectly.  Thanks in advance for your help.

### PR DESCRIPTION
**Pull request by patw0929**
Also fixed #275.

### CODE REVIEW

**Comment by maxcodes** [comment]
This also fixes #267

**Comment by avishayil** [comment]
@jkasten2 can you confirm?

**Comment by tapz** [comment]
Does this fix the deprecated calls in RCTOneSignal.m and will getPermissionSubscriptionState and addSubscriptionObserver be used instead of IdsAvailable?

**Comment by sean-roberts** [comment]
Anything I can do to help usher this through? I am waiting on this before I release my notifications feature - currently the experience is pretty broken without the fixes in the newer versions.

**Comment by patw0929** [comment]
@tapz: Sorry, due to I am not familiar with iOS native programming, so I am not sure how to implement the thing you mentioned.

Can anyone help to check it?  And is it the reason not to merge?
Thanks!

**Pull request merged**
