### PR TITLE
Fixed iOS framework linking by including the native SDK source

### PR DESCRIPTION
**Pull request by jkasten2**
* Added the full source of the OneSignal iOS native SDK to this project.
   - This the latest 2.3.5 version.
* Update RCTOneSignal.xcodeproj to reference and build the full SDK from source.
* Improved iOS steps and added "Add Required Capabilities section" that was missing before.
* Since the source is now included in the project remove references to use Cocoapods or install it.
   - Added manual update as a backup when a fix is needed quickly.

### CODE REVIEW

**Comment by jkasten2** [comment]
To test this pull request with a new project follow these steps.
```
react-native init AwesomeProject
cd AwesomeProject
npm install --save git://github.com/jkasten2/react-native-onesignal#ios_linking_and_header_fix_with_source
react-native link react-native-onesignal
```

Then follow the new readme steps below.
https://github.com/jkasten2/react-native-onesignal/tree/ios_linking_and_header_fix_with_source#installation

**Comment by GeoffreyPlitt** [comment]
+1

**Comment by avishayil** [comment]
@jkasten2 Thanks, i'll test it as soon as i'll have some time.

**Comment by avishayil** [comment]
@haxtrujillo, @vedovato, @dguillamot, @bitsal, @rustykey, @eriksape, @kelset, @edo1493, @larryranches, @mrpatiwi could you please help testing here guys?

**Comment by kelset** [comment]
How can I test it with my project? How to install via npm @jkasten2 version? Does it work as fix for v2? Or is it only v3 related?

**Comment by avishayil** [comment]
@kelset Just follow @jkasten2 instructions in this PR.
By the way, there is no v2 anymore, just v3. They're both compatible with RN >= 0.40 and RN <= 0.39.

**Comment by eriksape** [comment]
@avishayil Tested with the PR and instructions of @jkasten2 

but now the RCTOneSignal.h doesn't find theOneSignal.h

**Comment by eriksape** [comment]
@avishayil  seems that build succeded if add to the header search paths

``
 $(SRCROOT)/../node_modules/react-native-onesignal/ios
``

and set it to recursive

screen shot 2017-02-10 at 2 22 57 pm

**Comment by jkasten2** [comment]
@eriksape Just tried a fresh project with my instructions above without any issues.

Are you updating from an older version of the plugin?

Can you confirm the line and file you are seeing the error on? Is it `ios/RCTOneSignal/RCTOneSignal.h`?
This was updated from `#import <OneSignal/OneSignal.h>` to `#import "OneSignal.h"` in the `RCTOneSignal.xcodeproj` as it is now part of the source of this project.
https://github.com/geektimecoil/react-native-onesignal/pull/187/commits/9e375bb35c14ebb9532aea85adb88fe8fd869434#diff-2e43c12bb257cc587f0a1ed84983430fL7

Which `xcodeproj` file did you have to add that line to the header search path? `RCTOneSignal.xcodeproj` or the root Xcode project?

**Comment by eriksape** [comment]
@jkasten2 I create another project right now, I followed your instructions, same result.

``
Which xcodeproj file did you have to add that line to the header search path? RCTOneSignal.xcodeproj or the root Xcode project?
``
It was the main xcodeproject

The first Time i only added 
`` $(SRCROOT)/../node_modules/react-native-onesignal/ios/RCTOneSignal ``

I thought that causes the ``OneSignal.h not found``

**Comment by jkasten2** [comment]
@eriksape Ah you are right, the root project can't find the header file without the search path. Just tried a few relative paths in the source to try and get this to work without it but looks like it is a requirement.

Adding an image here that will be used as the source for the readme.
image

Did everything else work for you after adding this?

**Comment by guilhermedecampo** [comment]
@jkasten2 what is the configuration for the `header search paths` on the RCTOneSignal.xcodeproj?

**Comment by jkasten2** [comment]
@guilhermedecampo It should be the root project, your app's build target. No changes are need to ` RCTOneSignal.xcodeproj`.

**Comment by guilhermedecampo** [comment]
@jkasten2 thank you!

**Comment by larryranches** [comment]
@jkasten2 @avishayil Sorry i've been offline for a few days and it seems like using yarn in the most recent version 3.0.3 now gets the "header issue" and doesn't build in xcode anymore.

Using this pr `"react-native-onesignal": "git://github.com/jkasten2/react-native-onesignal.git#ios_linking_and_header_fix",` was and still is building in xcode.

Was there any changes to the setup in the latest 3.0.3?

**Comment by avishayil** [comment]
@larryranches Make sure you followed the latest instructions here https://github.com/geektimecoil/react-native-onesignal#adding-search-paths

**Comment by larryranches** [comment]
@avishayil Thanks! I'll try that out

**Comment by GeoffreyPlitt** [comment]
Did that, now getting "ld: framework not found OneSignal".

**Comment by guilhermedecampo** [comment]
@larryranches I had problems with yarn usage of this command:

`npm install --save git://github.com/jkasten2/react-native-onesignal#ios_linking_and_header_fix_with_source`

Maybe there is a diff way to use git links in yarn.

But since it's already merged no worries! 

Thank you @jkasten2 for the awesome work.

**Pull request merged**
